### ISSUE TITLE
Better support for large `map_size`

### ISSUE THREAD

**Issue by acdxvfsvd** [nyx-fuzz/packer#25]
By default `ld_preload_fuzz` reads `host_config.bitmap_size` from the configuration and maps a memory area with the corresponding size, then it overwrites `agent_config.coverage_bitmap_size` when processing an LTO-compiled binary but doesn't reallocate the memory.
```c
trace_buffer = mmap((void*)NULL, host_config.bitmap_size, PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, -1, 0);
memset(trace_buffer, 0xff, host_config.bitmap_size);
// ...
if (get_harness_state()->afl_mode && __afl_final_loc_ptr){
    unsigned int map_size = __afl_final_loc == 0 ? 65536 : __afl_final_loc;
    agent_config.coverage_bitmap_size = map_size;
}
``` 
There is no such argument about `bitmap_size` when generating configuration using `nyx_config_gen.py`, so the value will come from the included `default_config_kernel.ron`, which is 0x10000. 
This works well in most cases but may crash when the `map_size` of the binary is larger than 0x10000. It would be great to reallocate the memory after detecting the `map_size`, or just add an argument to the config generator for customizing the `map_size`.

**Comment by schumilo** [comment]
I was able to successfully reproduce the bug and it seems that my patch has now fixed the issue.
